debug: true
plugins:
  workflow:
    enabled: true
    params:
      workflow_path: ./example/workflows/
  web:
    enabled: false
    params:
      host: localhost
      port: 8090
  cron:
    enabled: true
    dependencies:
      - workflow
    params:
      cron_path: ./example/crons/
  hello_world:
    enabled: true